### ISSUE TITLE
关于背景图

### ISSUE THREAD

**Issue by 791136190** [ufownl/fake_chs_lp#1]
麻烦问一下你使用的背景图，是自己生成的还是在网上找的，我看了一下你这个图和网上别人用的背景图很像，但是蓝色的颜色不一样，你的是偏浅色，网上的是深蓝色的。如果是你自己生成的，能提供一下生成背景的方法吗，因为我像生成其它类型的背景图。

**Comment by ufownl** [comment]
背景图都是从网上找的

**Comment by 791136190** [comment]
好的，感谢，我已经找到部分其它车牌背景图了。
